language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6
script:
  - mvn test install
deploy:
  provider: releases
  api_key:
    secure: kkqXGlM3b8jeuMUsU/iy2Mvtns0VFaCr0Gx7RoW5AoG/oeBpd9tP5jxhLmshQRxmb5O5KK1BcaqhWiJ2Ii1rHT44I5DXLjdNW4a78zB0dMuykKKvukT3hwXDUbIWyKEkItMr+173FK/V9ePj/+uXviDbpnlUjsTSwlxfEgPlRsNk2paHYQ4k7N71R0bt+JqPIaxtpfd9EhvLsuGRj2MYM4KcLUqbuWh2L8wjUb7U7yWn2wMWRtCtde+t2qILit7XcsDzv83rNXTZzarQONeb+88lE/lMIhSo7ygXXbHYoxSlvtXt3fYm6UpF8SemTvvbi1zr+R4vSLN1Mi2tkc/asOGv1LaOGpb93NMmNiUezjmCDT3BsNY4nB2n/IEfgLPZ8vJDTj8LailmgyTayQIIzn1w06PFBrCTBM1rFe4JuOrB7Ncn7HOnYS3U1AVMxrFXweRMblyL96Y/BHj+2eQHxrcn4H3WJcM6ZHeEXFktYOIeCSfLezWwfFGXl7s2VvqWGYkEmp/0bk4LfPciGWUew8hwVgxSzDLvsIub8QuQSxXPlSaKvlQ2OnBdphvYdjhjyCzQe71TcrlR2Xhr6N1S/wEv1/7JC2Wiu3c0YZ7J2RWgfEjiZM5d9svNHLLMFJ3n9wpkCUb/zcBhcL3prw4r8EOhKnbslq6WidHqAkRGbU8=
  file: zorka-dist/target/netuitive-zorka.zip
  skip_cleanup: true
  on:
    tags: true
    jdk: oraclejdk8
